export const INPUT_EMAIL = 'INPUT_EMAIL';
export const INPUT_PASSWORD = 'INPUT_PASSWORD';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_APPLICATION_POSTS = 'SET_APPLICATION_POSTS';
export const SET_SIGN_IN_RESPONSE = 'SET_SIGN_IN_RESPONSE';
export const UPDATE_APP = 'UPDATE_APP';
export const CLEAR_APP_STATE = 'CLEAR_APP_STATE';
